force-app/main/default/objects/Star_Wars_Planet__c/Star_Wars_Planet__c.object-meta.xml
<CustomObject>
    <label>Star Wars: Planet</label>
    <nameField>
        <label>Star Wars: Planets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Star Wars: Planets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Climate__c.field-meta.xml
<CustomField>
    <fullName>Climate__c</fullName>
    <label>Climate</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Diameter__c.field-meta.xml
<CustomField>
    <fullName>Diameter__c</fullName>
    <label>Diameter</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Gravity__c.field-meta.xml
<CustomField>
    <fullName>Gravity__c</fullName>
    <label>Gravity</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Orbital_Period__c.field-meta.xml
<CustomField>
    <fullName>Orbital_Period__c</fullName>
    <label>Orbital Period</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Population__c.field-meta.xml
<CustomField>
    <fullName>Population__c</fullName>
    <label>Population</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Rotation_Period__c.field-meta.xml
<CustomField>
    <fullName>Rotation_Period__c</fullName>
    <label>Rotation Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Surface_Water__c.field-meta.xml
<CustomField>
    <fullName>Surface_Water__c</fullName>
    <label>Surface Water</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/Terrain__c.field-meta.xml
<CustomField>
    <fullName>Terrain__c</fullName>
    <label>Terrain</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Link to API source</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/StarWarsAPIFlow.cls
public class  StarWarsAPIFlow {
    @InvocableMethod(label='Get Star Wars Records' description='HTTP request to SWAPI.com' category='StarWars')
    public static List<Star_Wars_Planet__c> StarWarsAPIFlow(List<FlowInputs> request){
     Http http = new Http();
      HttpRequest req = new HttpRequest();
      req.setMethod('GET');
      req.setEndpoint('https://swapi.dev/api/planets/' + request[0].planetNumber);
      System.debug('request: '+request);
      req.setHeader('Accept', 'application/json;charset=UTF-8');
        
      List<Star_Wars_Planet__c> planetList = new List<Star_Wars_Planet__c>();
      //Instantiating the wrapper class for the JSON response from the Star Wars API
      GetPlanetsWrapperClass planetResponse = new GetPlanetsWrapperClass();

      try {
        HttpResponse response = http.send(req);
        if (
          response.getStatusCode() >= 200 &&  
          response.getStatusCode() <= 300
        ) {
          System.debug(response.getBody());
          planetResponse = (GetPlanetsWrapperClass) (JSON.deserialize(
            response.getBody(),
            GetPlanetsWrapperClass.class
          ));
        }
      } catch (System.CalloutException e) {
        System.debug('Callout error: ' + e);
      }

      Star_Wars_Planet__c newPlanet = new Star_Wars_Planet__c();
      if (planetResponse.name == null) {
        newPlanet.Name = 'No Data in the API';
        planetList.add(newPlanet);
      } else {
        //Creating new Salesforce record with the data populated
        newPlanet.Name = planetResponse.name;
        newPlanet.Climate__c = planetResponse.climate;
        newPlanet.Diameter__c = planetResponse.diameter;
        newPlanet.Gravity__c = planetResponse.gravity;
        newPlanet.Orbital_Period__c = planetResponse.orbital_period;
        newPlanet.Population__c = planetResponse.population;
        newPlanet.Rotation_period__c = planetResponse.surface_water;
        newPlanet.Terrain__c = planetResponse.terrain;
        newPlanet.Surface_Water__c = planetResponse.surface_water;
        newPlanet.URL__c = planetResponse.url;
        
        planetList.add(newPlanet);
      }
      insert planetList;
      return planetList;
    }
        //input details that comes to apex from flow
        public class FlowInputs{
    
            //@InvocableVariable
            //public Account accountSobj;
            
            @InvocableVariable
            public Integer planetNumber;
            
        }
}