force-app/main/default/objects/Star_Wars_Person__c/Star_Wars_Person__c.object-meta.xml
<CustomObject>
    <label>Star Wars: Person</label>
    <nameField>
        <label>Person&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Star Wars: People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star_Wars_Person__c/fields/Birth_Year__c.field-meta.xml
<CustomField>
    <fullName>Birth_Year__c</fullName>
    <label>Birth Year</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Person__c/fields/Eye_Color__c.field-meta.xml
<CustomField>
    <fullName>Eye_Color__c</fullName>
    <label>Eye Color</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Person__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Person__c/fields/Hair_Color__c.field-meta.xml
<CustomField>
    <fullName>Hair_Color__c</fullName>
    <label>Hair Color</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Person__c/fields/Height_cm__c.field-meta.xml
<CustomField>
    <fullName>Height_cm__c</fullName>
    <label>Height (cm)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Person__c/fields/Homeworld__c.field-meta.xml
<CustomField>
    <fullName>Homeworld__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Homeworld</label>
    <referenceTo>Star_Wars_Planet__c</referenceTo>
    <relationshipLabel>Residents</relationshipLabel>
    <relationshipName>Star_Wars_People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Person__c/fields/Mass_kg__c.field-meta.xml
<CustomField>
    <fullName>Mass_kg__c</fullName>
    <label>Mass (kg)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Planet__c/Star_Wars_Planet__c.object-meta.xml
<CustomObject>
    <label>Star Wars: Planet</label>
    <nameField>
        <label>Star Wars: Planets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Star Wars: Planets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star_Wars_Planet__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Link to API source</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/GetPeopleAPICallout.cls
/*******************************************************************************************
 * @Name         GetPeopleAPICallout
 * @Author       Adam Dalton
 * @Date         01/11/2023
 * @Group        Star Wars API Project
 * @Description  This class contains the HTTP 'GET' request that will grab the person data from swapi.dev/api and populate the Star_Wars_Person__c custom object in the Salesforce Org
 *******************************************************************************************/
/* MODIFICATION LOG
 * Version          Developer          Date               Description
 *-------------------------------------------------------------------------------------------
 *  1.0              Adam      01/09/2023          Initial Creation
 *  2.0              Adam      01/12/2023         Created a for loop so that the method iterates through all the endpoints in the API and create a new record
 *******************************************************************************************/
public with sharing class GetPeopleAPICallout {
  /**************************************************************************************
   * @Description  Future method to get Star Wars "Person" data from Open API and then insert a new Star_Wars_Person__c record with the related data
   * @Param		N/A
   * @Return       Void
   * @Example
   **************************************************************************************/
  @future(callout=true)
  public static void getPeople() {
    List<Star_Wars_Person__c> peopleList = new List<Star_Wars_Person__c>();
    for (Integer i = 1; i <= 83; i++) {
      Http http = new Http();
      HttpRequest req = new HttpRequest();
      req.setMethod('GET');
      req.setEndpoint('https://swapi.dev/api/people/' + i);
      req.setHeader('Accept', 'application/json;charset=UTF-8');

      //Instantiating the wrapper class for the JSON response from the Star Wars API
      GetPeopleWrapperClass peopleResponse = new GetPeopleWrapperClass();

      try {
        HttpResponse response = http.send(req);
        if (response.getStatusCode() == 200) {
          System.debug(response.getBody());
          peopleResponse = (GetPeopleWrapperClass) (JSON.deserialize(
            response.getBody(),
            GetPeopleWrapperClass.class
          ));
        }
      } catch (System.CalloutException e) {
        System.debug('Callout error: ' + e);
      }
      //Star_Wars_Planet__c homeworld = [SELECT Id FROM Star_Wars_Planet__c WHERE Url__c = :peopleResponse.homeworld LIMIT 1];

      //Creating new Salesforce record with the data populated
      Star_Wars_Person__c newPerson = new Star_Wars_Person__c();
      newPerson.Name = peopleResponse.name;
      newPerson.Birth_Year__c = peopleResponse.birth_year;
      newPerson.Eye_Color__c = peopleResponse.eye_color;
      newPerson.Gender__c = peopleResponse.gender;
      newPerson.Hair_Color__c = peopleResponse.hair_color;
      newPerson.Height_cm__c = peopleResponse.height;
      //newPerson.Homeworld__c  = homeworld.Id;
      newPerson.Mass_kg__c = peopleResponse.mass;
      newPerson.URL__c = peopleResponse.url;
      peopleList.add(newPerson);
    }
    insert peopleList;
  }
}