force-app/main/default/objects/Star_Wars_Person__c/Star_Wars_Person__c.object-meta.xml
<CustomObject>
    <label>Star Wars: Person</label>
    <nameField>
        <label>Person&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Star Wars: People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star_Wars_Starship__c/Star_Wars_Starship__c.object-meta.xml
<CustomObject>
    <label>Star Wars: Starship</label>
    <nameField>
        <label>Starship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Star Wars: Starships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Pilots__c.field-meta.xml
<CustomField>
    <fullName>Pilots__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pilots</label>
    <referenceTo>Star_Wars_Person__c</referenceTo>
    <relationshipLabel>Starships</relationshipLabel>
    <relationshipName>Star_Wars_Starships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Starship_Person_Junction__c/Starship_Person_Junction__c.object-meta.xml
<CustomObject>
    <description>Junction object between people and starships</description>
    <label>Starship_Person_Junction</label>
    <nameField>
        <label>Starship Person Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Starship_Person_Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Starship_Person_Junction__c/fields/PIlots__c.field-meta.xml
<CustomField>
    <fullName>PIlots__c</fullName>
    <label>Pilots</label>
    <referenceTo>Star_Wars_Starship__c</referenceTo>
    <relationshipLabel>Pilots</relationshipLabel>
    <relationshipName>Pilots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Starship_Person_Junction__c/fields/Starships__c.field-meta.xml
<CustomField>
    <fullName>Starships__c</fullName>
    <label>Starships</label>
    <referenceTo>Star_Wars_Person__c</referenceTo>
    <relationshipLabel>Starships</relationshipLabel>
    <relationshipName>Starship_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScheduledStarshipAPI.cls
global class ScheduledStarshipAPI Implements Schedulable {
    global void execute(SchedulableContext sc)
    {
        ScheduledStarshipAPI();
    }
    
    @future(callout=true)
    public static void ScheduledStarshipAPI() {
        List<Star_Wars_Starship__c> starshipRecords = new List<Star_Wars_Starship__c>();
        
        Integer pageNumber = 1;
        String nextPage = ' ';

        do{
            String starshipURL = 'https://swapi.dev/api/starships/?page=' + String.valueOf(pageNumber);
            StarshipWrapperv2 starshipResponse = StarWarsAPIRequest.starshipAPIrequest(starshipURL);
            List<StarshipWrapperv2.Results> starshipList = starshipResponse.results;
            nextPage = starshipResponse.next;

            for(StarshipWrapperv2.Results starship:starshipList){
                Star_Wars_Starship__c newStarship = StarWarsCreateRecords.createStarshipRecord(starship);
                starshipRecords.add(newStarship);
            }
            pageNumber++;
        }while(nextPage !=null);
        upsert starshipRecords URL__c;
      }
        

     

     /*   List<String> pilotURLS = starshipResponse.pilots;
        Id starshipId = [SELECT Id From Star_Wars_Starship__c WHERE URL__c = :starshipResponse.url LIMIT 1].Id; 
        List<Star_Wars_Person__c> pilotList = [SELECT Id,Name, URL__c FROM Star_Wars_Person__c WHERE URL__c IN :pilotURLS];

        for(Star_Wars_Person__c pilot: pilotList){
            Starship_Person_Junction__c newJunction = new Starship_Person_Junction__c();
            newJunction.Name = pilot.Name+' Starship relationship';
            newJunction.Pilots__c = pilot.Id;
            newJunction.Starships__c = starshipId;
            System.debug(newJunction);
            junctionList.add(newJunction);
        }

      }
      insert junctionList;*/
      
    
}