force-app/main/default/objects/Star_Wars_Starship__c/Star_Wars_Starship__c.object-meta.xml
<CustomObject>
    <label>Star Wars: Starship</label>
    <nameField>
        <label>Starship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Star Wars: Starships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Cargo_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Capacity__c</fullName>
    <label>Cargo Capacity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Consumables__c.field-meta.xml
<CustomField>
    <fullName>Consumables__c</fullName>
    <label>Consumables</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Crew__c.field-meta.xml
<CustomField>
    <fullName>Crew__c</fullName>
    <label>Crew</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Hyperdrive_Rating__c.field-meta.xml
<CustomField>
    <fullName>Hyperdrive_Rating__c</fullName>
    <label>Hyperdrive Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Max_Atmosphering_Speed__c.field-meta.xml
<CustomField>
    <fullName>Max_Atmosphering_Speed__c</fullName>
    <label>Max Atmosphering Speed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Passengers__c.field-meta.xml
<CustomField>
    <fullName>Passengers__c</fullName>
    <label>Passengers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Pilots__c.field-meta.xml
<CustomField>
    <fullName>Pilots__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pilots</label>
    <referenceTo>Star_Wars_Person__c</referenceTo>
    <relationshipLabel>Starships</relationshipLabel>
    <relationshipName>Star_Wars_Starships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Star_Wars_Starship__c/fields/Starship_Class__c.field-meta.xml
<CustomField>
    <fullName>Starship_Class__c</fullName>
    <label>Starship Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetStarShipAPICallout.cls
/*******************************************************************************************
* @Name         GetStarShipAPICallout 
* @Author       Adam Dalton 
* @Date         01/11/2023
* @Group        Star Wars API Project
* @Description  This class contains the HTTP 'GET' request that will grab the planet data from swapi.dev/api and populate the Star_Wars_Starship__c custom object in the Salesforce Org
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0              Adam      01/09/2023          Initial Creation                                                      
*******************************************************************************************/
public with sharing class GetStarShipAPICallout {
/**************************************************************************************
* @Description  Future method to get Star Wars "Starship" data from Open API and then insert a new Star_Wars_Starship__c record with the related data
* @Param		N/A
* @Return       Void 
* @Example     
**************************************************************************************/     
    @future (callout=true)
    public static void getStarships(){
        
        Integer i = Integer.valueof((Math.random() * 28)+1);
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint('https://swapi.dev/api/starships/'+i);
        req.setHeader('Accept', 'application/json;charset=UTF-8');

        //Instantiating the wrapper class for the JSON response from the Star Wars API
        GetStarshipWrapperClass starshipResponse = new GetStarshipWrapperClass();

        try {
            HttpResponse response = http.send(req);
                if(response.getStatusCode() == 200 || response.getStatusCode() == 201){
                    System.debug(response.getBody());
                    starshipResponse = (GetStarshipWrapperClass)(JSON.deserialize(response.getBody(), GetStarshipWrapperClass.class));
            }
        } catch(System.CalloutException e) {
            System.debug('Callout error: '+ e);
        }

        //Creating new Salesforce record with the Starship data populated
        Star_Wars_Starship__c newStarship = new Star_Wars_Starship__c ();
            newStarship.Name                      = starshipResponse.name;
            newStarship.Cargo_Capacity__c         = double.valueOf(starshipResponse.cargo_capacity);
            newStarship.Consumables__c            = starshipResponse.consumables;
            newStarship.Crew__c                   = starshipResponse.crew;
            newStarship.Hyperdrive_Rating__c      = double.valueOf(starshipResponse.hyperdrive_rating);
            newStarship.Length__c                 = double.valueOf(starshipResponse.length);
            newStarship.Manufacturer__c           = starshipResponse.manufacturer;
            newStarship.Max_Atmosphering_Speed__c = starshipResponse.max_atmosphering_speed;
            newStarship.Model__c                  = starshipResponse.model;
            newStarship.Passengers__c             = starshipResponse.passengers;
            //newStarship.Pilots__c = starshipResponse
            newStarship.Starship_Class__c          = starshipResponse.starship_class;
            newStarship.URL__c                    = starshipResponse.url;
        insert newStarship;

    }

}